ARG RUBY_VERSION=3.3.11
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential git libpq-dev libvips libyaml-dev pkg-config postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_PATH="/usr/local/bundle" \
    RAILS_ENV=development

RUN bundle config set without ""

COPY Gemfile Gemfile.lock ./
RUN bundle install

RUN bundle binstubs bundler --force