services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      bash -c "./wait-for-db.sh db &&
      bundle exec rails db:create db:migrate &&
      bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mortgage_api_development
      TEST_DATABASE_URL: postgres://postgres:password@db:5432/mortgage_api_test
      RAILS_ENV: development
